version: "3.9"
services:
  web:
    container_name: apiapp
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    links:
      - node
    volumes:
      - .:/app
  node:
    container_name: node
    image: node:16-alpine3.15