version: "3.9"
services:

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mapadmin:vW7KvHJ>VZl@mongo:27017/clinical_map'

  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mapadmin
      MONGO_INITDB_ROOT_PASSWORD: vW7KvHJ>VZl
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: