version: "3.9"
services:
  web:
    container_name: webapp
    build: .
    ports:
      - "4000:4000"
    links:
      - node
    image: testcomposer.azurecr.io/test:latest
  node:
    container_name: node
    image: testcomposer.azurecr.io/node:16