# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clinicalmap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://clinicalmapapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ec6dc9f618804799b35bca176df3067a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d147859aa31f4e41a1842009662ffe27 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: clinicalmapapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec6dc9f618804799b35bca176df3067a }}/clinicalmapapi.azurecr.io/clinical-map:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clinicalmap'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_47935f5a0ce441d78ed6f4ac8770eb54 }}
        images: 'clinicalmapapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec6dc9f618804799b35bca176df3067a }}/clinicalmapapi.azurecr.io/clinical-map:${{ github.sha }}'